### Start the Simulation of Subscription
GET http://localhost:8803/sim/start

> {%
client.global.set("startCol", "true")
client.test("Start Collection ..", function() {
  client.assert(response.status == "200","Did NOT start WF!")
})

%}
